### ISSUE TITLE
Is the code missing?

### ISSUE THREAD

**Issue by MirSoul** [mir-ethernity/mir-eternal#161]
Hello, thank you for your great work. I want to ask you a little question,
#140 Whether the problem is missing or not, I can't see any trace of repair in the relevant code
#77 Is there any missing problem? In my test, I still click to disconnect the link
Thank you again for your efforts

**Comment by bernatvadell** [comment]
Relatet to: #140 

https://github.com/Suprcode/mir-eternal/commit/118fb4d194808a5a66dff6b1cb291e9e6fc689ab

![image](https://user-images.githubusercontent.com/17298604/191819870-ae95d111-11b8-420e-8b60-689dbb22f2db.png)

![image](https://user-images.githubusercontent.com/17298604/191819904-8ec4a1b6-1b7a-48c2-91d7-f9114fe1abd1.png)

Related to #77 i'll check what is the problem and say you things

**Comment by MirSoul** [comment]
Sorry, this is my mistake. I asked about # 140 without testing.

**Comment by MirSoul** [comment]
![Snipaste_2022-09-23_11-22-37](https://user-images.githubusercontent.com/111971172/191887004-7cad5211-797f-41d7-970b-c2786018300c.png)
![Snipaste_2022-09-23_11-24-48](https://user-images.githubusercontent.com/111971172/191887006-47ec9897-6339-418a-b89b-d56b9000bd86.png)
The above processes are related to the occurrence of BUGs.

**Comment by MirSoul** [comment]
[CapturePackets_20220923032830.zip](https://github.com/Suprcode/mir-eternal/files/9630594/CapturePackets_20220923032830.zip)
The above is all data checked from clicking NPC to completing warehouse lock
The middle part of the data has a mobile phone verification code, please ignore it

**Comment by MirSoul** [comment]
[CapturePackets_20220923032830.zip](https://github.com/Suprcode/mir-eternal/files/9630595/CapturePackets_20220923032830.zip)

**Comment by bernatvadell** [comment]
Thanks for the collaboration!

I would need one more packet capture where you enter the wrong code.

implemented ref: https://github.com/Suprcode/mir-eternal/commit/f07b3ca8bf37f78511473f7c6f1bbd5d5dd31500

At the moment the SMS verification system is integrated (since we don't have integration with a messaging provider, at the moment the message appears in the GS logs, surely, the integration will be done by mail instead of SMS).

![image](https://user-images.githubusercontent.com/17298604/191926665-2f927edd-562b-471c-9a1b-60d52874ffb8.png)

And this is what it looks like on the client:

![image](https://user-images.githubusercontent.com/17298604/191926872-06a42670-c493-4c93-b44c-30975d6197a1.png)

![image](https://user-images.githubusercontent.com/17298604/191926919-6b1ea5bf-a1b4-4ab6-bbe5-95aa30978c22.png)

![image](https://user-images.githubusercontent.com/17298604/191926957-3ffb208c-dfbe-41b1-a7f4-e291ff2810c0.png)

**Comment by MirSoul** [comment]
As you wish。
Click NPC to enter error three times, and cannot enter again within five minutes
[CapturePackets_Click NPC to enter error three times, and cannot enter again within five minutes.zip](https://github.com/Suprcode/mir-eternal/files/9635625/CapturePackets_Click.NPC.to.enter.error.three.times.and.cannot.enter.again.within.five.minutes.zip)

**Comment by MirSoul** [comment]
This is the data package that can be opened and closed freely during the current login period after correct input
[CapturePackets_20220923165129.zip](https://github.com/Suprcode/mir-eternal/files/9635664/CapturePackets_20220923165129.zip)
