### ISSUE TITLE
IP: x.x.x.x Info: Logged tickets do not exist.

### ISSUE THREAD

**Issue by liutongechao** [mir-ethernity/mir-eternal#208]
Hi, I encountered the above issue. 
I added a `server `file in the account server directory and a `ServerCfg.txt` file in the launcher directory. I can successfully log in, but when trying to enter the game, connection failed and I saw this error in the game server console.
BTW, it happened on the remote server but local deployment is fine.

**Comment by liutongechao** [comment]
When I opened all server ports, the game worked fine. Previously, I only opened port 7000 UDP and port 8701 TCP. Did I miss other ports?

**Comment by bernatvadell** [comment]
In the README.md you find a diagram of the communications and ports that are used.

As you indicate, you should only open ports 8701 and 7000, the rest are for internal communication.

What could be happening, is that you have set the public IP instead of the internal IP.

![image](https://github.com/mir-ethernity/mir-eternal/assets/17298604/46a0d6ee-db17-4372-87d4-ea33e5e0f2d3)
